name: kindli
description: "Kindli - A gentle approach to building better habits."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  intl: ^0.19.0
  dotted_border: ^2.1.0
  flutter_svg: ^2.0.10+1
  sign_in_with_apple: ^6.1.3
  google_sign_in: ^6.2.1
  google_sign_in_ios: 5.7.0
  sign_in_button: ^3.2.0
  device_info_plus: ^9.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/images/kindli_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
  - family: Sora
    fonts:
      - asset: assets/fonts/Sora-Regular.ttf
        weight: 400
      - asset: assets/fonts/Sora-Medium.ttf
        weight: 500
      - asset: assets/fonts/Sora-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Sora-Bold.ttf
        weight: 700
        
  - family: DMSans            # ‚Üê ADD THIS SECTION
    fonts:
      - asset: assets/fonts/DMSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/DMSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/DMSans-SemiBold.ttf
        weight: 600